### ISSUE TITLE
Make it possible to use DartClojure from ClojureScript

### ISSUE THREAD

**Issue by PEZ** [Liverm0r/DartClojure#8]
I want to add a Dart->Clojure converter to Calva:

* https://github.com/BetterThanTomorrow/calva/issues/1763

The way easiest way to do this would be that DartClojure was made to work with ClojureScript, because Calva code can then do the conversion.

I have forked and am converting things to `cljc`. Of course running into many interesting problems, but I am making some progress. 😄 Are you interested in a PR?

**Comment by Liverm0r** [comment]
Sorry, didn't see it yesterday. Already reviewed your pr :)

**Comment by PEZ** [comment]
🚀
